### ISSUE TITLE
обновить зависимости

### ISSUE THREAD

**Issue by ituman** [mindblowingly/BOLT_PROJECT#8]

**Comment by dchebakov** [comment]
Ты не подключал dependabot?

**Comment by ituman** [comment]
нет

**Comment by ituman** [comment]
ты для номотеха предлагал какую-то другую штуку для проверки обновлений, может ее заюзать? dependabot опять будет надоедать своими ПРами

**Comment by dchebakov** [comment]
Видимо, это новая фишка гитхаба надоедать депендаботом
Они его просто купили в том году
